### ISSUE TITLE
Segfault when comparing feeds

### ISSUE THREAD

**Issue by kgaughan** [kgaughan/mercury#2]
I believe this might be something to do with some particular RSS feed not including a published date or something:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x3918bc]

goroutine 1 [running]:
main.feedQueue.Less(0x22bb200, 0x57, 0x80, 0x20f7200, 0x57, 0x80, 0x50, 0x4f, 0x64b01)
        mercury/feedqueue.go:35 +0x150
container/heap.down(0x4deed8, 0x209f6e0, 0x27, 0x57, 0x209f301)
        container/heap/heap.go:109 +0x104
container/heap.Init(0x4deed8, 0x209f6e0)
        container/heap/heap.go:46 +0x5c
main.main()
        mercury/main.go:95 +0x864
```
I'll investigate this, but I think the solution would be to filter out any bad feed items like this.

**Comment by kgaughan** [comment]
Turns out that some feeds don't include a publication date on entries, which is a tad annoying.
